"""CUDA 13 block-tree DEVICE/HOST/DISK cases from the upstream smoke suite."""

import pytest

from rtp_llm.test.smoke_framework.manifest import build_smoke_params
from rtp_llm.test.smoke_framework.runner import run_smoke_test

SMOKE_CASES = {'smoke_v4_flash_pd_cp2ep2_dp2ep2_mtp_page_rr_logits_block_tree_device_only_sm100': {'task_info': 'data/model/deepseek_v4/q_r_v4_flash_pd_cp2ep2_dp2ep2_mtp_page_rr_logits_block_tree_device_only_sm100_arm.json',
                                                                                     'smoke_args': {'prefill': '--load_method '
                                                                                                               'fastsafetensors '
                                                                                                               '--max_seq_len '
                                                                                                               '8192 '
                                                                                                               '--enable_cuda_graph '
                                                                                                               '0 '
                                                                                                               '--act_type '
                                                                                                               'BF16 '
                                                                                                               '--tp_size '
                                                                                                               '2 '
                                                                                                               '--ep_size '
                                                                                                               '2 '
                                                                                                               '--world_size '
                                                                                                               '2 '
                                                                                                               '--seq_size_per_block '
                                                                                                               '1024 '
                                                                                                               '--kernel_seq_size_per_block '
                                                                                                               '128 '
                                                                                                               '--role_type '
                                                                                                               'PREFILL '
                                                                                                               '--cache_store_rdma_mode '
                                                                                                               '0 '
                                                                                                               '--use_local '
                                                                                                               '1 '
                                                                                                               '--reuse_cache '
                                                                                                               '1 '
                                                                                                               '--enable_device_cache '
                                                                                                               '1 '
                                                                                                               '--enable_memory_cache '
                                                                                                               '0 '
                                                                                                               '--enable_disk_cache '
                                                                                                               '0 '
                                                                                                               '--enable_remote_cache '
                                                                                                               '0 '
                                                                                                               '--test_block_num '
                                                                                                               '34 '
                                                                                                               '--use_deepep_moe '
                                                                                                               '1 '
                                                                                                               '--use_deepep_low_latency '
                                                                                                               '0 '
                                                                                                               '--cp_rotate_method '
                                                                                                               'ALL_GATHER '
                                                                                                               '--prefill_cp_kv_cache_sharded '
                                                                                                               '1 '
                                                                                                               '--reserver_runtime_mem_mb '
                                                                                                               '65536 '
                                                                                                               '--max_context_batch_size '
                                                                                                               '1 '
                                                                                                               '--fp8_kv_cache '
                                                                                                               '1 '
                                                                                                               '--sp_type '
                                                                                                               'mtp '
                                                                                                               '--gen_num_per_cycle '
                                                                                                               '3 '
                                                                                                               '--sp_model_type '
                                                                                                               'deepseek_v4_mtp '
                                                                                                               '--sp_checkpoint_path '
                                                                                                               '/mnt/nas1/hf/DeepSeek-V4-Flash '
                                                                                                               '--sp_act_type '
                                                                                                               'bf16',
                                                                                                    'decode': '--load_method '
                                                                                                              'fastsafetensors '
                                                                                                              '--max_seq_len '
                                                                                                              '8192 '
                                                                                                              '--enable_cuda_graph '
                                                                                                              '1 '
                                                                                                              '--act_type '
                                                                                                              'BF16 '
                                                                                                              '--tp_size '
                                                                                                              '1 '
                                                                                                              '--dp_size '
                                                                                                              '2 '
                                                                                                              '--ep_size '
                                                                                                              '2 '
                                                                                                              '--world_size '
                                                                                                              '2 '
                                                                                                              '--seq_size_per_block '
                                                                                                              '1024 '
                                                                                                              '--kernel_seq_size_per_block '
                                                                                                              '128 '
                                                                                                              '--role_type '
                                                                                                              'DECODE '
                                                                                                              '--cache_store_rdma_mode '
                                                                                                              '0 '
                                                                                                              '--use_local '
                                                                                                              '1 '
                                                                                                              '--reuse_cache '
                                                                                                              '1 '
                                                                                                              '--enable_device_cache '
                                                                                                              '1 '
                                                                                                              '--enable_memory_cache '
                                                                                                              '0 '
                                                                                                              '--enable_disk_cache '
                                                                                                              '0 '
                                                                                                              '--enable_remote_cache '
                                                                                                              '0 '
                                                                                                              '--use_deepep_moe '
                                                                                                              '1 '
                                                                                                              '--use_deepep_low_latency '
                                                                                                              '1 '
                                                                                                              '--load_cache_timeout_ms '
                                                                                                              '120000 '
                                                                                                              '--reserver_runtime_mem_mb '
                                                                                                              '49152 '
                                                                                                              '--fp8_kv_cache '
                                                                                                              '1 '
                                                                                                              '--sp_type '
                                                                                                              'mtp '
                                                                                                              '--gen_num_per_cycle '
                                                                                                              '3 '
                                                                                                              '--sp_model_type '
                                                                                                              'deepseek_v4_mtp '
                                                                                                              '--sp_checkpoint_path '
                                                                                                              '/mnt/nas1/hf/DeepSeek-V4-Flash '
                                                                                                              '--sp_act_type '
                                                                                                              'bf16 '
                                                                                                              '--cp_rotate_method '
                                                                                                              'PREFILL_CP '
                                                                                                              '--prefill_cp_kv_cache_sharded '
                                                                                                              '1 '
                                                                                                              '--prefill_cp_size '
                                                                                                              '2'},
                                                                                     'envs': {'prefill': ['DSV4_USE_FRAMEWORK_KV=1',
                                                                                                          'LOG_LEVEL=DEBUG'],
                                                                                              'decode': ['DSV4_USE_FRAMEWORK_KV=1']},
                                                                                     'sleep_time_qr': 1,
                                                                                     'gpu_type': 'L20D_TEST',
                                                                                     'platform': 'cuda',
                                                                                     'markers': ['smoke',
                                                                                                 'cuda',
                                                                                                 'L20D_TEST'],
                                                                                     'timeout': 600,
                                                                                     'data_root': 'oss'},
 'smoke_v4_flash_pd_cp2ep2_dp2ep2_mtp_page_rr_logits_block_tree_only_memory_sm100': {'task_info': 'data/model/deepseek_v4/q_r_v4_flash_pd_cp2ep2_dp2ep2_mtp_page_rr_logits_block_tree_only_memory_sm100_arm.json',
                                                                                     'smoke_args': {'prefill': '--load_method '
                                                                                                               'fastsafetensors '
                                                                                                               '--max_seq_len '
                                                                                                               '8192 '
                                                                                                               '--enable_cuda_graph '
                                                                                                               '0 '
                                                                                                               '--act_type '
                                                                                                               'BF16 '
                                                                                                               '--tp_size '
                                                                                                               '2 '
                                                                                                               '--ep_size '
                                                                                                               '2 '
                                                                                                               '--world_size '
                                                                                                               '2 '
                                                                                                               '--seq_size_per_block '
                                                                                                               '256 '
                                                                                                               '--kernel_seq_size_per_block '
                                                                                                               '128 '
                                                                                                               '--role_type '
                                                                                                               'PREFILL '
                                                                                                               '--cache_store_rdma_mode '
                                                                                                               '0 '
                                                                                                               '--use_local '
                                                                                                               '1 '
                                                                                                               '--reuse_cache '
                                                                                                               '1 '
                                                                                                               '--enable_device_cache '
                                                                                                               '0 '
                                                                                                               '--enable_memory_cache '
                                                                                                               '1 '
                                                                                                               '--enable_disk_cache '
                                                                                                               '0 '
                                                                                                               '--enable_remote_cache '
                                                                                                               '0 '
                                                                                                               '--memory_cache_size_mb '
                                                                                                               '32 '
                                                                                                               '--memory_cache_sync_timeout_ms '
                                                                                                               '120000 '
                                                                                                               '--test_block_num '
                                                                                                               '23 '
                                                                                                               '--use_deepep_moe '
                                                                                                               '1 '
                                                                                                               '--use_deepep_low_latency '
                                                                                                               '0 '
                                                                                                               '--cp_rotate_method '
                                                                                                               'ALL_GATHER '
                                                                                                               '--prefill_cp_kv_cache_sharded '
                                                                                                               '1 '
                                                                                                               '--reserver_runtime_mem_mb '
                                                                                                               '65536 '
                                                                                                               '--max_context_batch_size '
                                                                                                               '1 '
                                                                                                               '--fp8_kv_cache '
                                                                                                               '1 '
                                                                                                               '--sp_type '
                                                                                                               'mtp '
                                                                                                               '--gen_num_per_cycle '
                                                                                                               '3 '
                                                                                                               '--sp_model_type '
                                                                                                               'deepseek_v4_mtp '
                                                                                                               '--sp_checkpoint_path '
                                                                                                               '/mnt/nas1/hf/DeepSeek-V4-Flash '
                                                                                                               '--sp_act_type '
                                                                                                               'bf16',
                                                                                                    'decode': '--load_method '
                                                                                                              'fastsafetensors '
                                                                                                              '--max_seq_len '
                                                                                                              '8192 '
                                                                                                              '--enable_cuda_graph '
                                                                                                              '1 '
                                                                                                              '--act_type '
                                                                                                              'BF16 '
                                                                                                              '--tp_size '
                                                                                                              '1 '
                                                                                                              '--dp_size '
                                                                                                              '2 '
                                                                                                              '--ep_size '
                                                                                                              '2 '
                                                                                                              '--world_size '
                                                                                                              '2 '
                                                                                                              '--seq_size_per_block '
                                                                                                              '256 '
                                                                                                              '--kernel_seq_size_per_block '
                                                                                                              '128 '
                                                                                                              '--role_type '
                                                                                                              'DECODE '
                                                                                                              '--cache_store_rdma_mode '
                                                                                                              '0 '
                                                                                                              '--use_local '
                                                                                                              '1 '
                                                                                                              '--reuse_cache '
                                                                                                              '1 '
                                                                                                              '--enable_device_cache '
                                                                                                              '0 '
                                                                                                              '--enable_memory_cache '
                                                                                                              '0 '
                                                                                                              '--enable_disk_cache '
                                                                                                              '0 '
                                                                                                              '--enable_remote_cache '
                                                                                                              '0 '
                                                                                                              '--use_deepep_moe '
                                                                                                              '1 '
                                                                                                              '--use_deepep_low_latency '
                                                                                                              '1 '
                                                                                                              '--load_cache_timeout_ms '
                                                                                                              '120000 '
                                                                                                              '--reserver_runtime_mem_mb '
                                                                                                              '49152 '
                                                                                                              '--fp8_kv_cache '
                                                                                                              '1 '
                                                                                                              '--sp_type '
                                                                                                              'mtp '
                                                                                                              '--gen_num_per_cycle '
                                                                                                              '3 '
                                                                                                              '--sp_model_type '
                                                                                                              'deepseek_v4_mtp '
                                                                                                              '--sp_checkpoint_path '
                                                                                                              '/mnt/nas1/hf/DeepSeek-V4-Flash '
                                                                                                              '--sp_act_type '
                                                                                                              'bf16 '
                                                                                                              '--cp_rotate_method '
                                                                                                              'PREFILL_CP '
                                                                                                              '--prefill_cp_kv_cache_sharded '
                                                                                                              '1 '
                                                                                                              '--prefill_cp_size '
                                                                                                              '2'},
                                                                                     'envs': {'prefill': ['DSV4_USE_FRAMEWORK_KV=1',
                                                                                                          'LOG_LEVEL=DEBUG'],
                                                                                              'decode': ['DSV4_USE_FRAMEWORK_KV=1']},
                                                                                     'sleep_time_qr': 1,
                                                                                     'gpu_type': 'L20D_TEST',
                                                                                     'platform': 'cuda',
                                                                                     'markers': ['smoke',
                                                                                                 'cuda',
                                                                                                 'L20D_TEST'],
                                                                                     'timeout': 600,
                                                                                     'data_root': 'oss'},
 'smoke_v4_flash_pd_cp2ep2_dp2ep2_mtp_page_rr_logits_block_tree_only_disk_sm100': {'task_info': 'data/model/deepseek_v4/q_r_v4_flash_pd_cp2ep2_dp2ep2_mtp_page_rr_logits_block_tree_only_disk_sm100_arm.json',
                                                                                   'smoke_args': {'prefill': '--load_method '
                                                                                                             'fastsafetensors '
                                                                                                             '--max_seq_len '
                                                                                                             '8192 '
                                                                                                             '--enable_cuda_graph '
                                                                                                             '0 '
                                                                                                             '--act_type '
                                                                                                             'BF16 '
                                                                                                             '--tp_size '
                                                                                                             '2 '
                                                                                                             '--ep_size '
                                                                                                             '2 '
                                                                                                             '--world_size '
                                                                                                             '2 '
                                                                                                             '--seq_size_per_block '
                                                                                                             '256 '
                                                                                                             '--kernel_seq_size_per_block '
                                                                                                             '128 '
                                                                                                             '--role_type '
                                                                                                             'PREFILL '
                                                                                                             '--cache_store_rdma_mode '
                                                                                                             '0 '
                                                                                                             '--use_local '
                                                                                                             '1 '
                                                                                                             '--reuse_cache '
                                                                                                             '1 '
                                                                                                             '--enable_device_cache '
                                                                                                             '0 '
                                                                                                             '--enable_memory_cache '
                                                                                                             '0 '
                                                                                                             '--enable_disk_cache '
                                                                                                             '1 '
                                                                                                             '--enable_remote_cache '
                                                                                                             '0 '
                                                                                                             '--disk_cache_staging_block_count '
                                                                                                             '2 '
                                                                                                             '--test_block_num '
                                                                                                             '23 '
                                                                                                             '--use_deepep_moe '
                                                                                                             '1 '
                                                                                                             '--use_deepep_low_latency '
                                                                                                             '0 '
                                                                                                             '--cp_rotate_method '
                                                                                                             'ALL_GATHER '
                                                                                                             '--prefill_cp_kv_cache_sharded '
                                                                                                             '1 '
                                                                                                             '--reserver_runtime_mem_mb '
                                                                                                             '65536 '
                                                                                                             '--max_context_batch_size '
                                                                                                             '1 '
                                                                                                             '--fp8_kv_cache '
                                                                                                             '1 '
                                                                                                             '--sp_type '
                                                                                                             'mtp '
                                                                                                             '--gen_num_per_cycle '
                                                                                                             '3 '
                                                                                                             '--sp_model_type '
                                                                                                             'deepseek_v4_mtp '
                                                                                                             '--sp_checkpoint_path '
                                                                                                             '/mnt/nas1/hf/DeepSeek-V4-Flash '
                                                                                                             '--sp_act_type '
                                                                                                             'bf16',
                                                                                                  'decode': '--load_method '
                                                                                                            'fastsafetensors '
                                                                                                            '--max_seq_len '
                                                                                                            '8192 '
                                                                                                            '--enable_cuda_graph '
                                                                                                            '1 '
                                                                                                            '--act_type '
                                                                                                            'BF16 '
                                                                                                            '--tp_size '
                                                                                                            '1 '
                                                                                                            '--dp_size '
                                                                                                            '2 '
                                                                                                            '--ep_size '
                                                                                                            '2 '
                                                                                                            '--world_size '
                                                                                                            '2 '
                                                                                                            '--seq_size_per_block '
                                                                                                            '256 '
                                                                                                            '--kernel_seq_size_per_block '
                                                                                                            '128 '
                                                                                                            '--role_type '
                                                                                                            'DECODE '
                                                                                                            '--cache_store_rdma_mode '
                                                                                                            '0 '
                                                                                                            '--use_local '
                                                                                                            '1 '
                                                                                                            '--reuse_cache '
                                                                                                            '1 '
                                                                                                            '--enable_device_cache '
                                                                                                            '0 '
                                                                                                            '--enable_memory_cache '
                                                                                                            '0 '
                                                                                                            '--enable_disk_cache '
                                                                                                            '0 '
                                                                                                            '--enable_remote_cache '
                                                                                                            '0 '
                                                                                                            '--use_deepep_moe '
                                                                                                            '1 '
                                                                                                            '--use_deepep_low_latency '
                                                                                                            '1 '
                                                                                                            '--load_cache_timeout_ms '
                                                                                                            '120000 '
                                                                                                            '--reserver_runtime_mem_mb '
                                                                                                            '49152 '
                                                                                                            '--fp8_kv_cache '
                                                                                                            '1 '
                                                                                                            '--sp_type '
                                                                                                            'mtp '
                                                                                                            '--gen_num_per_cycle '
                                                                                                            '3 '
                                                                                                            '--sp_model_type '
                                                                                                            'deepseek_v4_mtp '
                                                                                                            '--sp_checkpoint_path '
                                                                                                            '/mnt/nas1/hf/DeepSeek-V4-Flash '
                                                                                                            '--sp_act_type '
                                                                                                            'bf16 '
                                                                                                            '--cp_rotate_method '
                                                                                                            'PREFILL_CP '
                                                                                                            '--prefill_cp_kv_cache_sharded '
                                                                                                            '1 '
                                                                                                            '--prefill_cp_size '
                                                                                                            '2'},
                                                                                   'envs': {'prefill': ['DSV4_USE_FRAMEWORK_KV=1',
                                                                                                        'LOG_LEVEL=DEBUG',
                                                                                                        'DISK_CACHE_PATHS=__TEST_TMPDIR__/disk_kv_only_disk_prefill0,__TEST_TMPDIR__/disk_kv_only_disk_prefill1',
                                                                                                        'DISK_CACHE_SIZE_MB=64',
                                                                                                        'DISK_CACHE_BUFFERED_IO=1',
                                                                                                        'DISK_CACHE_SYNC_TIMEOUT_MS=120000'],
                                                                                            'decode': ['DSV4_USE_FRAMEWORK_KV=1']},
                                                                                   'sleep_time_qr': 2,
                                                                                   'gpu_type': 'L20D_TEST',
                                                                                   'platform': 'cuda',
                                                                                   'markers': ['smoke',
                                                                                               'cuda',
                                                                                               'L20D_TEST'],
                                                                                   'timeout': 600,
                                                                                   'data_root': 'oss'}}

_test_params = build_smoke_params(
    pytest, {"smoke_cuda13_cache_tiers": SMOKE_CASES}, composite_suites={}
)


@pytest.mark.parametrize("test_name,test_config", _test_params)
def test_smoke_cuda13_cache_tiers(test_name, test_config):
    run_smoke_test(test_name, test_config)
